# TODO: cleanup
format = """\
[](#242f33)\
[\uf120 ](bg:#242f33)\
[](bg:#6791C9 fg:#242f33)\
[  ](bg:#6791C9 fg:#000000)\
$directory\
[](fg:#6791C9 bg:#313c40)\
$git_branch\
$git_status\
[](fg:#313c40 bg:#242f33)\
$username\
[ ](fg:#242f33)\
$cmd_duration\
$git_metrics\
"""

[line_break]
disabled = true

[username]
disabled = false
style_user = "bg:#242f33"
style_root = "bg:#242f33"
format = '[   $user ](fg:#e4e6e7 $style)'

[directory]
style = "bg:#6791C9 fg:black"
format = "[$path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "../"

[directory.substitutions]
"Documents" = "Documents  "
"Downloads" = "Downloads  "
"Music" = "Music  "
"Pictures" = "Pictures "

[git_branch]
symbol = " "
style = "bg:#313c40 fg:#e4e6e7"
format = '[[ $symbol $branch ](bg:#313c40 fg:#e4e6e7)]($style)'

[git_status]
style = "bg:#313c40"
format = '[[($all_status$ahead_behind )](bg:#313c40 fg:#e4e6e7)]($style)'

[cmd_duration]
min_time = 1000
style = "bg:light blue"
show_milliseconds = false
format = "[[[](fg:#6791C9) $duration](fg:black bg:#6791C9) ](fg:#6791C9)"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"
format = '[+$added]($added_style)/[-$deleted ]($deleted_style)'
