add_newline = false
scan_timeout = 10

format = """
(fg:#89b4fa)$time$username$directory$git_branch$git_status$shell$character"""

[line_break]
disabled = false

[fill]
symbol = " "
style = "fg:#252525 bg:#302D41"

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"

[battery]
full_symbol = ""
format = "[ $symbol$percentage ](fg:#89b4fa)"

[[battery.display]]
threshold = 100

[time]
format = '[\[$time\] ](fg:#89b4fa bg:#302D41)'
utc_time_offset = "local"
time_format = "%T"
disabled = false
time_range = "-"

[git_branch]
format = "[$symbol$branch](bg:#252525)[ ](fg:#252525 bg:#302D41 bold)"
symbol = " "

[shell]
bash_indicator = "[](fg:#c4c431 bg:#302D41)[BSH-MODE](fg:#89b4fa bg:#c4c431)[](fg:#c4c431 bg:#302D41)[  ](fg:#c4c431 bg:#302D41)[](fg:#302D41)"
zsh_indicator = "[](fg:#94b3a8 bg:#302D41)[ZSH-MODE](fg:#89b4fa bg:#94b3a8)[](fg:#94b3a8 bg:#302D41)[  ](fg:#94b3a8 bg:#302D41)[](fg:#302D41)"
nu_indicator = "[](fg:#fe6142 bg:#302D41)[NSH-MODE](fg:#89b4fa bg:#fe6142)[](fg:#fe6142 bg:#302D41)[  ](fg:#fe6142 bg:#302D41)[](fg:#302D41)"
fish_indicator = "[](fg:#5442f5 bg:#302D41)[FSH-MODE](fg:#89b4fa bg:#5442f5)[](fg:#5442f5 bg:#302D41)[  ](fg:#5442f5 bg:#302D41)[](fg:#302D41)"
elvish_indicator = "[](fg:#a742f5 bg:#302D41)[ESH-MODE](fg:#89b4fa bg:#a742f5)[](fg:#a742f5 bg:#302D41)[  ](fg:#a742f5 bg:#302D41)[](fg:#302D41)"
xonsh_indicator = "[](fg:#70ff24 bg:#302D41)[XSH-MODE](fg:#89b4fa bg:#70ff24)[](fg:#70ff24 bg:#302D41)[  ](fg:#70ff24 bg:#302D41)[](fg:#302D41)"
unknown_indicator = "[](fg:#89b4fa bg:#302D41)[???-MODE][](fg:#302D41)"
style = "fg:#89b4fa bg:#302D41"
disabled = true

[directory]
format = "[$path]($style)[$read_only](fg:#fff bg:#302D41)[ ](fg:#302D41 bg:#252525 bold)"
style = "fg:#89b4fa bg:#302D41"
truncation_symbol = "…/"
truncate_to_repo = false
truncation_length = 100
home_symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]](fg:#89b4fa bg:#302D41)[ ](fg:#89b4fa bg:#302D41))'

[username]
format = "[](fg:#89b4fa bold)[ ](fg:#252525 bg:#89b4fa bold)[ ](fg:#89b4fa bg:#302D41 bold)"
show_always = true
disabled = false